{
 "title": "Devops Nodes Overview",
 "description": "Overview of K8s Cluster Nodes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=~\"^(system|user)$\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "load1" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_load1[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(node_memory_MemFree_bytes, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes, \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Received",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[5m])",
     "legendFormat": "{{instance}} ({{device}})"
    }
   ]
  },
  {
   "title": "Transmitted",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "{{instance}} ({{device}})"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[5m]) / 1000 * 100",
     "legendFormat": "{{instance}} ({{role}} - {{device}})"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[5m]) * 512 + rate(node_disk_written_bytes_total[5m]) * 512",
     "legendFormat": "{{instance}} - {{device}})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_filesystem_free_bytes / node_filesystem_size_bytes * 100",
     "legendFormat": "{{instance}} - {{device}} - {{mountpoint}} ({{fstype}})"
    }
   ]
  }
 ]
}